### ISSUE TITLE
Error installing CellProfiler by pip

### ISSUE THREAD

**Issue by webcluster4u** [CellProfiler/core#70]
Hi,

I am trying to install cellprofiler by pip and my environment is windows10 and python 3.8

```
C:\Users\Mahdi\Downloads\pyzmq-18.0.1.tar\dist\pyzmq-18.0.1\pyzmq-18.0.1>python -m pip install cellprofiler
Collecting cellprofiler
  Using cached CellProfiler-4.0.7-py3-none-any.whl (24.6 MB)
Collecting Pillow>=7.1.0
  Downloading Pillow-8.1.0-cp38-cp38-win_amd64.whl (2.2 MB)
     |████████████████████████████████| 2.2 MB 1.6 MB/s
Collecting numpy==1.19.3
  Downloading numpy-1.19.3-cp38-cp38-win_amd64.whl (13.3 MB)
     |████████████████████████████████| 13.3 MB 1.3 MB/s
Collecting docutils==0.15.2
  Using cached docutils-0.15.2-py3-none-any.whl (547 kB)
Collecting python-bioformats==4.0.0
  Using cached python_bioformats-4.0.0-py3-none-any.whl (35.3 MB)
Collecting wxPython>=4.1.0
  Downloading wxPython-4.1.1-cp38-cp38-win_amd64.whl (18.1 MB)
     |████████████████████████████████| 18.1 MB 1.3 MB/s
Collecting boto3>=1.12.28
  Downloading boto3-1.17.5-py2.py3-none-any.whl (130 kB)
     |████████████████████████████████| 130 kB 1.7 MB/s
Collecting scikit-learn>=0.20
  Using cached scikit_learn-0.24.1-cp38-cp38-win_amd64.whl (6.9 MB)
Collecting inflect>=2.1
  Downloading inflect-5.0.2-py3-none-any.whl (31 kB)
Collecting scikit-image>=0.17.2
  Downloading scikit_image-0.18.1-cp38-cp38-win_amd64.whl (12.2 MB)
     |████████████████████████████████| 12.2 MB 1.3 MB/s
Collecting mysqlclient==1.4.6
  Downloading mysqlclient-1.4.6-cp38-cp38-win_amd64.whl (263 kB)
     |████████████████████████████████| 263 kB 1.3 MB/s
Collecting matplotlib==3.1.3
  Downloading matplotlib-3.1.3-cp38-cp38-win_amd64.whl (9.1 MB)
     |████████████████████████████████| 9.1 MB 1.3 MB/s
Collecting python-javabridge==4.0.0
  Using cached python-javabridge-4.0.0.tar.gz (1.3 MB)
Collecting centrosome==1.2.0
  Using cached centrosome-1.2.0.tar.gz (777 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
Collecting imageio>=2.5
  Using cached imageio-2.9.0-py3-none-any.whl (3.3 MB)
Collecting six
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting pyzmq==18.0.1
  Using cached pyzmq-18.0.1.tar.gz (1.2 MB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Mahdi\Downloads\python38\python-3.8.0-embed-amd64\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Mahdi\\AppData\\Local\\Temp\\pip-install-79efhrta\\pyzmq_f9e08c403f7c4fc5a7423f852c9f3b2e\\setup.py'"'"'; __file__='"'"'C:\\Users\\Mahdi\\AppData\\Local\\Temp\\pip-install-79efhrta\\pyzmq_f9e08c403f7c4fc5a7423f852c9f3b2e\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Mahdi\AppData\Local\Temp\pip-pip-egg-info-ebnd3zar'
         cwd: C:\Users\Mahdi\AppData\Local\Temp\pip-install-79efhrta\pyzmq_f9e08c403f7c4fc5a7423f852c9f3b2e\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Mahdi\AppData\Local\Temp\pip-install-79efhrta\pyzmq_f9e08c403f7c4fc5a7423f852c9f3b2e\setup.py", line 55, in <module>
        from buildutils import (
    ModuleNotFoundError: No module named 'buildutils'
```

It can almost install all dependencies except pyzmq .1.18.0 giving me above error!

I am not sure how to resolve above error.

**Comment by bethac07** [comment]
Hi, 

Do you have the C++ libraries and [other things](https://github.com/CellProfiler/CellProfiler/wiki/Source-installation-%28Windows%29) from this wiki page installed?
